name = "anime-table"
compatibility_date = "2025-10-26"
pages_build_output_dir="dist"

[vars]
AUTH_URL = "https://myanimelist.net/v1/oauth2/authorize"
TOKEN_URL = "https://myanimelist.net/v1/oauth2/token"
API_URL = "https://api.myanimelist.net/v2"
